route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
      - smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: AKIAQ3EGVPKUIITLP7UY
        auth_password: BPiVa+zeBu5Fu8qNjaleYlWE4OkCYU8nu6WHgzUW8ITJ
        from: gonepadususmithareddy917@gmail.com
        to:  susmithagonepadu.devops@gmail.com
        headers:
          subject: Prometheus Mail Alert
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']